nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://4a63-2605-59c0-1e17-e910-6e1d-4245-3c0-355b.ngrok-free.app"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs