nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://b070-2605-59c0-1e17-e910-4707-855b-4f3-ea3b.ngrok-free.app"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs