nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://ccae-2605-59c0-1ed0-4d10-2ceb-da15-93a7-6081.ngrok-free.app"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs